// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj8XBnFzJ9lOKKwhMAVKpgZOoFKgVZ-JE',
    appId: '1:414249738488:web:c80cff2fd42c9855a65b0d',
    messagingSenderId: '414249738488',
    projectId: 'fire-bcd6c',
    authDomain: 'fire-bcd6c.firebaseapp.com',
    storageBucket: 'fire-bcd6c.appspot.com',
    measurementId: 'G-4DHNSJC34V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoRMcyDTLn2neFcKRw2ymBevZWWcHO1dQ',
    appId: '1:414249738488:android:6ae7be3421b235b4a65b0d',
    messagingSenderId: '414249738488',
    projectId: 'fire-bcd6c',
    storageBucket: 'fire-bcd6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI9IhJThBvtfbQpOuFC9cp74fKudRxOBA',
    appId: '1:414249738488:ios:f0f47a224842b97ba65b0d',
    messagingSenderId: '414249738488',
    projectId: 'fire-bcd6c',
    storageBucket: 'fire-bcd6c.appspot.com',
    iosClientId: '414249738488-838gbdleeq07m1mur249slsov0f2rsol.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI9IhJThBvtfbQpOuFC9cp74fKudRxOBA',
    appId: '1:414249738488:ios:f0f47a224842b97ba65b0d',
    messagingSenderId: '414249738488',
    projectId: 'fire-bcd6c',
    storageBucket: 'fire-bcd6c.appspot.com',
    iosClientId: '414249738488-838gbdleeq07m1mur249slsov0f2rsol.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireNew',
  );
}
